server:
  port: 8001
spring:
  datasource:
    #?????????
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql???
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank1?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: '0507'

  rabbitmq:
    username: zzz
    password: zzz
    virtual-host: /
    addresses: 117.72.32.234:5672
    publisher-confirm-type: correlated
    publisher-returns: true